spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mynotes
    username: mynotes
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop/update
    show-sql: true

